name: Assignment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}

          scripts: |
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh

            touch .env
            echo "${{ secrets.ENV_FILE }}" > .env
            cat .env
            nvm install 14
            npm install -g pm2
            cd ~/var/www/backend/news-category-predictor
            git pull origin master
            npm install
            npm install bcryptjs
            pm2 restart backend
