name: Assignment

on:
  push:
   branches:
    - main 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.04]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        users: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: npm install and build
        run: |
          npm install
          npm run build

        env:
          CI: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
            
          scripts: |
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh

            touch .env
            echo "${{ secrets.ENV_FILE }}" > .env
            cat .env
            nvm install 14
            npm install -g pm2
            cd ~/var/www/backend/news-category-predictor
            git pull master
            npm install
            npm install bcryptjs
            pm2 restart backend  

    